services:
  backend:
    build: .
    command: ["/app/.venv/bin/uvicorn","src.backend.main:app","--host=0.0.0.0","--port=8000"]
    ports: ["8000:8000"]
    volumes: [".:/app"]
    environment:
      PYTHONPATH: /app

  frontend:
    build: .
    command: streamlit run src/frontend/app.py --server.address 0.0.0.0 --server.port 8501
    ports: ["8501:8501"]
    volumes: [".:/app"]
    environment:
      PYTHONPATH: /app
    depends_on: [backend]
